---
  apiversion : apps/v1
  kind : Deployment
  metadata : 
    name : hubrest
  spec :
    replicas : 3
    selector : 
      matchLabels : 
        app : hubrest
    template :
      metadata :
        labels :
          app : hubrest
      spec :
        containers:
          - name: hubrest
            image: tushartyagi07/get-started:part1
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8081  # Should match the port number that the Go application listens on
              livenessProbe:           # To check the health of the Pod
                httpGet:
                  path: /user
                  port: 8081
                  scheme: POST
                initialDelaySeconds: 5
                periodSeconds: 15
                timeoutSeconds: 5
              readinessProbe:          # To check if the Pod is ready to serve traffic or not
                httpGet:
                  path: /users
                  port: 8081
                  scheme: GET
                initialDelaySeconds: 5
                timeoutSeconds: 1    


      

