---
    apiVersion: v1
    kind: Service                    
    metadata:
      name: hubrest-service   
    spec:
      type: NodePort                 
      ports:                         
      - name: http
        port: 9090
        targetPort: 8081
      selector:
        app: hubrest         